services:
  - type: web
    name: telegram-bot
    env: python
    pythonVersion: "3.10.13"  # Добавьте эту строку
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CREATOR_CHAT_ID
        sync: false
      - key: WEBHOOK_URL
        sync: false
    plan: free
    autoDeploy: true
